plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.142'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

sourceSets.main.resources {
    srcDir('src/generated/resources')

    exclude("**/*.bbmodel")
    exclude("src/generated/**/.cache")
}

repositories {
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven {
        name = "Sleeping Town"
        url = "https://repo.sleeping.town/"
    }

    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }

    maven {
        name 'Xander Maven'
        url 'https://maven.isxander.dev/releases'
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }

    repositories {
        maven { url 'https://maven.blamejared.com' }
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            jvmArgument("-Dmixin.debug.export=true")
            jvmArgument("-Dmixin.debug.verbose=true")
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly ("dev.emi:emi-neoforge:${emi_version}:api")
    compileOnly ("dev.emi:emi-neoforge:${emi_version}")

    compileOnly "curse.maven:reliable-emi-1411826:8686700"
    compileOnly "maven.modrinth:yacl:${yacl_version}-neoforge"

    compileOnly("mezz.jei:jei-${minecraft_soft_version}-neoforge-api:${jei_version}")
    compileOnly "vazkii.patchouli:Patchouli:${patchouli_version}:api"
    compileOnly "vazkii.patchouli:Patchouli:${patchouli_version}"

    compileOnly "curse.maven:emi-recipe-sharing-1587795:8570049"

    if (project.hasProperty("withEmi")) {
        localRuntime "dev.emi:emi-neoforge:${emi_version}"
    }

    if (project.hasProperty("withReliable")) {
        localRuntime "curse.maven:reliable-emi-1411826:8686700"
        localRuntime "maven.modrinth:yacl:${yacl_version}-neoforge"
    }

    if (project.hasProperty("withJei")) {
        localRuntime "mezz.jei:jei-${minecraft_soft_version}-neoforge:${jei_version}"
    }

    if (project.hasProperty("withSharing")) {
        implementation "curse.maven:emi-recipe-sharing-1587795:8570049"
    }

    // for testing extra non vanilla recipes
    if (project.hasProperty("withVitae")) {
        implementation "curse.maven:modonomicon-538392:8532346"
        implementation "curse.maven:geckolib-388172:8350073"
        implementation "curse.maven:neovitae-1404763:8767463"
    }

    if (project.hasProperty("withSupplementaries")) {
        implementation "curse.maven:selene-499980:8749776"
        implementation "curse.maven:supplementaries-412082:8244187"
    }

    if (project.hasProperty("withPatchouli")) {
        runtimeOnly "vazkii.patchouli:Patchouli:${patchouli_version}"
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' }

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
